### ISSUE TITLE
Preserving order?

### ISSUE THREAD

**Issue by kud1ing** [rusthon/Rusthon#23]
Maybe this is not how it's supposed to work. I tried to call the Rusthon generated code from C++ like this:

    ```rusthon
    #backend:c++

    class HelloWorld:
        def mymethod(self):
                print("hello world " + str(42))
    ```
    ```c++
    int main()
    {
        HelloWorld h;
        h.mymethod();
    }
    ```

This does not work, because the inline C++ code ends up at the top of the generated C++ file, not at the bottom. At this point `HelloWorld` is not defined yet.

Is this supposed to work?

**Comment by hartsantler** [comment]
This should work, but it hasn't been implemented yet.  The assumption I made when I first hard-coded it this way, is that you (the user) are most likely to use handwritten C++ before your Rusthon code, because your handwritten C++ code is likely there to wrap some other external libraries, and you need wrapper functions that can be called from Rusthon.

In any case, the index of the code block is saved when the markdown is parsed, so that can be used to fix this.  see `rusthon.py` for how this works.

**Comment by kud1ing** [comment]
I came across this situation because the hello world alone does not link due to a missing main function.
My first reaction was to write a main() in C++ rather than in Rusthon.

**Comment by kud1ing** [comment]
Well I also wanted to see where it is possible to define a native main().
I think that's not possible in Haxe.

**Comment by hartsantler** [comment]
It is a good idea to preserve order, it just takes a little refactoring of the code in rusthon.py
