### ISSUE TITLE
Language Freeze 

### ISSUE THREAD

**Issue by jcrubino** [rusthon/Rusthon#49]
Can we consider a feature freeze so a very basic stdlib functionality it ubiquitous across the main supported languages?  HTTP specifically.

The project might deserve the name "Hydra" at this point.

**Comment by hartsantler** [comment]
We are pretty much at a feature freeze now.  I will not introduce anymore frontends or backends for Rusthon 1.0.

**Comment by hartsantler** [comment]
The last thing that should be integrated is Nuitka.  This should allow easy integration with CPython, libpython.

new performance improvements: http://nuitka.net/posts/nuitka-progress-2014.html

**Comment by jcrubino** [comment]
So nuitika would be the main compiler?

**Comment by hartsantler** [comment]
The typed version of rusthon IS NOT compatible with the new upcomming type annotations for python3.  I had looked at MyPy awhile back, and I did not like the naming conventions.

**Comment by jcrubino** [comment]
Details, since you know have lots of experience with a type system for Python... what works what does not?  It might be important for both projects.

The benefits of closer compatibility with Python are obvious if you want the project to grow.

**Comment by hartsantler** [comment]
Rusthon has some very different type syntax from MyPy.  A 2D array in Rusthon is `[][]T` similar to Go syntax.  In MyPy i'm not sure, but its probably something like `Array(Array(T))`

The syntax for a callback type is probably very different, Rusthon has `def f( callback:lambda()() ):` for lambda functions, and `def f( callback:func()() )` to work with external C.  MyPy likely has some very different syntax for callbacks.

I could not take MyPy seriously because local variables are typed using special comments.
```python
a = b #type: T
```

Rusthon has a better type system for local variables:
```python
let a : T = b
```

**Comment by jcrubino** [comment]
Not intending to inject too much indirection into the project but food for thought...

Might it be a good direction to focus on js, obj-c/swift and android java and go for a python-esque mobile + web developer platform with backend support?

**Comment by hartsantler** [comment]
I am giving up on Nuitka for now, because going direct generating CPython C-API calls from our own syntax works better and is much simpler solution to embed libpython.

**Comment by jcrubino** [comment]
ok.

What are the practical end user applications of Rusthon going to be?

**Comment by hartsantler** [comment]
The end user is likely to be somebody that needs to connect with a large and complex c++ code base like UnrealEngine4, and want's to do it with a Python like language, and may also want to embed libPython, or other VM's like Java.  

The end user may also want to customize the transpiler or compiler in someway, and that is pretty easy to do in Rusthon because its all written in Python, and not too large.

**Comment by hartsantler** [comment]
Better interop with C++ requires `::` namespace syntax.

**Comment by hartsantler** [comment]
closing this issue because the syntax for all backends has become consistent and is stable in the javascript backend.  the other backends still need some bugs worked out, but all the syntax rules and gotcha''s has been uncovered.
