### ISSUE TITLE
Nice example but

### ISSUE THREAD

**Issue by v3ss0n** [rusthon/Rusthon#79]
`with 𝕄`

 but how the hell i type that  𝕄  :astonished:

**Comment by hartsantler** [comment]
unicode is totally optional.  i used it in the example because it makes the use of mini-macros very clear.
 
i do not know of any text editors that allow you to type in unicode mathematical-alphanumerics, so you have to copy and paste from your system character map program.

for those who want to use unicode characters, the options is there, it is a trade-off between readability and type-ability.
